upstream project-hotelsa_app {
    server project-hotelsa-app-1:9000;
    server project-hotelsa-app-2:9000;
    server project-hotelsa-app-3:9000;
}
 
server {
    listen 80;
    index index.php index.html;
    server_name ujikom-absen14.net;
    root /var/www/public;
 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location ~ \.php$ {
        fastcgi_pass project-hotelsa_app;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
 
        add_header X-Upstream-Server $upstream_addr always;
    }
 
    location ~ /\.ht { deny all; }
}
